service: MeuCofrinho

plugins:
  - serverless-esbuild
  - serverless-deployment-bucket

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-east-1"}
  environment: ${file(./serverless/provider/environment.yml)}
  # iam:
  #   role: ${file(./serverless/provider/iam.yml)}
  deploymentBucket:
    name: ${self:custom.SECRETS.DEPLOYMENT_BUCKET}
functions:
  Api:
    handler: src/main.ApiHandler
    timeout: 30
    events:
      - http:
          method: ANY
          path: /{proxy+}
          cors: false
      - http:
          method: ANY
          path: /
          cors: false

# resources:
#   - ${file(./serverless/resources/sqs.yml)}

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - 'src/**/*.js'
    - 'data/*'

custom: ${file(./serverless/custom/variables.yml)}
