service: MeuCofrinho

plugins:
  - serverless-esbuild
  - serverless-deployment-bucket

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, "dev"}
  region: ${opt:region, "us-east-1"}
  environment: ${file(./serverless/provider/environment.yml)}
  deploymentBucket:
    name: ${opt:stage, "dev"}-eratechnologies-deployment-bucket
  # iam:
  #   role: ${file(./serverless/provider/iam.yml)}

functions:
  Api:
    handler: src/main.ApiHandler
    timeout: 30
    events:
      - http:
          method: ANY
          path: /{proxy+}
          cors: false
      - http:
          method: ANY
          path: /
          cors: false

custom: ${file(./serverless/custom/variables.yml)}

resources:
  - ${file(./serverless/resources/sqs-message-queue.yml)}
  - ${file(./serverless/resources/dynamo-account-table.yml)}
